version: '3.8'

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: GFGF18101961
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - backend
    depends_on:
      - postgres

  orbit:
    image: andrusha0502/orbit:v1.7
    container_name: orbit-app
    restart: always
    ports:
      - "8888:8888"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: GFGF18101961
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: muurakamiii/satellite-tracker:latest
    container_name: hackfront
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_USE_MOCK: "true"
      NEXT_PUBLIC_ENABLE_WS: "false"
      NEXT_PUBLIC_API_URL: "http://157.22.175.181:8888"
    networks:
      - backend
    depends_on:
      - orbit